name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ runner.os }}-build
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-${{ runner.os }}-build

      - run: |
          if [ -d "Library" ]; then
            rm -rf Library
          fi
          mkdir -p Library

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-logFile -'

      - name: List files in Library directory
        run: |
          echo "Listing files in Library directory:"
          ls -al Library

      - name: List files in root directory
        run: |
          echo "Listing files in root directory:"
          ls -al /github/workspace

      - name: Display Editor log
        if: always()
        run: |
          if [ -f /github/workspace/Library/Editor.log ]; then
            cat /github/workspace/Library/Editor.log
          else
            echo "Editor.log does not exist."
          fi

      - name: Display Unity log
        if: always()
        run: |
          if [ -f /github/workspace/Library/Unity.log ]; then
            cat /github/workspace/Library/Unity.log
          else
            echo "Unity.log does not exist."
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
