name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: windows-2022
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Cache Library folder
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/Assets/**') }}
          restore-keys: |
            ${{ runner.os }}-unity-library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      # Output
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

  # Clean up cache
  clean-cache:
    runs-on: windows-2022
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Delete Library folder
        run: |
          if (Test-Path -Path "Library") {
            Remove-Item -Path "Library" -Recurse -Force
          }
