name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: windows-2022
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Cache Library folder
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/Assets/**') }}
          restore-keys: |
            ${{ runner.os }}-unity-library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildMethod: CustomBuildProcessor.CustomBuildMethod

      # List files in build directory for debugging
      - name: List build directory
        run: |
          echo "Listing contents of Builds directory:"
          dir build

      # Output
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: D:\a\Novel\Novel\build  # Убедитесь, что этот путь совпадает с местом сохранения вашего билда